### ISSUE TITLE
Sunflower

### ISSUE THREAD

**Issue by Tsunayoshi** [Crypt1-C/Encrypted_-Modpack#103]
Hi,

is there any way to get a Sunflower? So far i tried to bone meal and golden egg the Sunflower biome in the normal world.
In the mining dimension the sunflower biome does not exist.
there are no rftoolsdimenions, so i am a bit lost if there is any way or not.

ty for ur time!

Edit: Is that maybe possible with the Space Quest row?

**Comment by koalalord9999** [comment]
Was pretty sure there was a way to craft them.. Lemme check real quick

**Comment by koalalord9999** [comment]
I couldnt find one, but theres recipes that use them... so there must be a way, I just dont know how.

**Comment by Tsunayoshi** [comment]
As far i found out, they can only spawn natural (https://minecraftpc.fandom.com/wiki/Sunflower). But i managed to write a script with a custom recipe to get them. Thanks for checking, i was unsure if there is a solution inside the pack. ♥
