### ISSUE TITLE
slow flight

### ISSUE THREAD

**Issue by DiViMii** [Crypt1-C/Encrypted_-Modpack#104]
I'm not sure if it's a bug or just some weird feature but when I fly it feels like levitating (by that i mean slow and slippery), but I can still control the altitude.
I think it happened after I ate one of the magic lollipops from Corail Tombstone and got one of the effects they can give.

**Comment by koalalord9999** [comment]
May have happened from collecting Ethereal Wings from Nameless trinkets

**Comment by DiViMii** [comment]
Unfortunately that's not the case.
It happens even after I take off all accessories and clear my inventory.

**Comment by DiViMii** [comment]
Unfortunately that's not the case.
It happens even after I take off all accessories and clear my inventory.

**Comment by koalalord9999** [comment]
if you can post a world download I might be able to look at it for you

**Comment by DiViMii** [comment]
here's the save file
https://1drv.ms/u/s!AnZaihH8PoBEgekcekTupZCuITIl7Q?e=KB5yLk

**Comment by koalalord9999** [comment]
Looking into it right now
Maybe I'll have some luck figureing it out

**Comment by koalalord9999** [comment]
From what I saw, it was defintely caused by the Ethereal Wings, however - since you no longer have them atleast in the save sent, you'll need to spawn them in, equip them, then remove them. You should be back to normal flight speed immediately afterwards. enjoy!
