### ISSUE TITLE
Can't join world

### ISSUE THREAD

**Issue by MarcelZabk** [Crypt1-C/Encrypted_-Modpack#12]
Can't play a world after creation, since the game crashes intantly after its generated

**Comment by ne0n1691** [comment]
Same, it crashes shortly after world creation at 2% roughly.
Heres the log incase you need it.
[latest.log](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9212510/latest.log)

**Comment by Crypt1-C** [comment]
@ne0n1691 you are using optifine which is unsupported in this modpack

@MarcelZabk that might be your case too

**Comment by MarcelZabk** [comment]
@Crypt1-C we already wrote on Discord, but no thats not my case and it seems you cant help me too by that...
