### ISSUE TITLE
Bug on 0.8 with Nether quest

### ISSUE THREAD

**Issue by Uplinks22** [Crypt1-C/Encrypted_-Modpack#13]
Visit the nether quest portal is ticked and says 100% but the quest cannot be completed. This is stopping from progressing to the Magicae quest line
![bug](https://user-images.githubusercontent.com/110172695/181504503-36239a54-b6fa-4c7d-84e3-0d79c79269f1.jpg)

**Comment by Crypt1-C** [comment]
fixed in newer versions
