### ISSUE TITLE
string drop

### ISSUE THREAD

**Issue by countoearl** [Crypt1-C/Encrypted_-Modpack#14]
string isn't dropping from oak trees or any tree

**Comment by jellonek** [comment]
It's something connected with whole ex nihilo sequentia mod configuration (or version) as worms are not dropping when crook is used, crucible does not accept any leaves/saplings/apples, the same issue is visible on wooden barrels.

**Comment by jellonek** [comment]
That happens probably only on first world created on 1.8. IDK if after restarting pack or just recreating new world - everything went back to normal.

**Comment by Crypt1-C** [comment]
Desync Issue
