### ISSUE TITLE
Stone generator from (iron generator mod) BUG

### ISSUE THREAD

**Issue by awsmaythem** [Crypt1-C/Encrypted_-Modpack#17]
hello ,
Am trying to break the stone generator with wood pickaxe it disappear (the generator i mean) please fix it

Best regards
Aws maythem

**Comment by Epicycle23** [comment]
What version are you using and is it a vanilla pickaxe?
There was a but in previous versions where tinker's pickaxes would destroy the generators.

**Comment by awsmaythem** [comment]
Encrypted_-Pre-release-1.8 and yes vanilla pickaxe and even the tinker stone pickaxe

**Comment by melbellrocks** [comment]
Also having this issue with a tinker's pickaxe on Release Version 1.1

**Comment by 3733WOLF** [comment]
This is an issue with tinkers, and without modifying the mod itself there's nothing we can do, use an appropriate level of vanilla to pick them up
