### ISSUE TITLE
Minecraft crashes on exit

### ISSUE THREAD

**Issue by Epicycle23** [Crypt1-C/Encrypted_-Modpack#18]
v1.8
Every time I quit minecraft from the main menu the game crashes without a crash report.
Can't find anything in the logs either.
Exit Code: -1073740940

**Comment by digitalseraphim** [comment]
This is still happening for me on 1.4. I'm wondering if it's related to the backup issue (#62)

**Comment by 3733WOLF** [comment]
actually its because of mahou tsukai not liking rubidium
