### ISSUE TITLE
How to obtain sponges?

### ISSUE THREAD

**Issue by Epicycle23** [Crypt1-C/Encrypted_-Modpack#20]
The Absorbers from RfToolsDimensions require a sponge, but I can't find any way to optain sponges.
The only way I could figure out is to create a RFTools-Dimension with a sponge-block or monument-feature dimlet, but to create the dimlet I need sponges.
I could in theory create random dimensions and hope for a monument to pop up but that feels kind of grindy/random.
Even tried the marine fisher but it does not seem to pick up sponges either it's been running for quite a while now.
So how are you supposed to obtain sponges?

**Comment by Crypt1-C** [comment]
there was an oversight about getting sponges will be fixed in future updates
