### ISSUE TITLE
Alchemistry issues

### ISSUE THREAD

**Issue by loadstones** [Crypt1-C/Encrypted_-Modpack#21]
The Alchemistry book can be crafted but has no info except the chapter headings.

The fission multiblock is I assume supposed to be a new configuration because of the quantity of items in the quest, but can't tell because book has no info. 

quest calls for 88 casings, 9 cores and 1 controller
old way is 98 casings, 3 cores and 1 controller

Built it the old way 5x5 hollow cube with 3 cores in center and controller on center edge, and it forms, and works, but shows -1 of -1 energy so basically doesn't seem to use any energy to split items.

Fusion multiblock quest seems to want  1 casing, 9 cores and 1 controller so not sure what to do with that

**Comment by Crypt1-C** [comment]
will work on adding a documentation to the multiblock
