### ISSUE TITLE
Old World incompatibility issue

### ISSUE THREAD

**Issue by VinceD70** [Crypt1-C/Encrypted_-Modpack#22]
Noticed after updating to Version 1.0, my world I had working in 0.8 ceased to load. Instead I hit a page saying "Error in currently selected datapacks prevented the world from loading." I had no success with the safe mode option nor finding a solution on my own by digging through the folders.
I have done a debug test by creating a new world, which works.
Below is the screen I hit after trying to load the old world, which I think I originally made in 0.6 of the pack.
![image](https://user-images.githubusercontent.com/2531137/182047127-706a2cdd-9d0d-40b4-bf76-b2af9c8a91ef.png)

**Comment by Epicycle23** [comment]
Yeah same with my world I even cleared my compact machines before updating because I saw the mod was removed but still won't load the old world, just started a new one -.-

**Comment by Epicycle23** [comment]
Seems to be something else than compact machines still gives the same error even with compact machines re-added.

**Comment by 3733WOLF** [comment]
Compact machines is the culprit, it adds a bunch of junk data behind in save files as such unfortunately we're not sure how to solve this one other then adding it back in and using a world backup from before you removed it
