### ISSUE TITLE
Minecraft crashes after pressing launch

### ISSUE THREAD

**Issue by fuckyou6712** [Crypt1-C/Encrypted_-Modpack#24]
after opening the launcher and pressing the play button, shortly after the launcher closes it opens again and gives an error code, ill copy and paste it here:

This crash may be caused by a java runtime issue
Exit code: 1

any idea on why it breaks?

Also i made this account just now specifficaly for this purpose, also i was still angry while making it.

**Comment by SleepyPopp** [comment]
Could you please send your latest.log? This doesn't really help besides the fact of it stated that it might be caused by a java runtime issue.
