### ISSUE TITLE
cant install the mod

### ISSUE THREAD

**Issue by Vortakofas** [Crypt1-C/Encrypted_-Modpack#25]
i press install start to download and just bug out and starts again

**Comment by SleepyPopp** [comment]
Does this have anything to do with the Modpack? Is this a launcher issue with CF or Other Third Party Launchers like MultiMC or GDLauncher or ATLauncher?

**Comment by Vortakofas** [comment]
thats just lauchers i told u curseforge dont even let me install it

**Comment by 3733WOLF** [comment]
The files are valid in curse, this sounds like an issue on your side, worse case scenario reinstall curse, it's a bug I've run into on multiple packs in the past
