### ISSUE TITLE
Many Many Crashes

### ISSUE THREAD

**Issue by DemonSlayer112** [Crypt1-C/Encrypted_-Modpack#26]
This modpack has been fun. But in previous versions it would crash when closing the client, never bothered me since i was closing anyways.
But now for 1.2 I made a new world in preparation for the Gobber mod.
It now crashed on joining a new world. First crash on creation:
[crash-2022-08-04_23.33.30-server.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9266065/crash-2022-08-04_23.33.30-server.txt)

Second crash on trying to join(after it got to 100%):

[crash-2022-08-04_23.40.14-server.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9266077/crash-2022-08-04_23.40.14-server.txt)
Log file with latest crash:
[latest.log](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9266087/latest.log)

It feels like by others they don't get such constant crashes. And I believe I given the client enough ram.

**Comment by th2m1** [comment]
Probably you should check your config, ip address and port:

ava.net.BindException: **Address already in use: bind**
