### ISSUE TITLE
JEI not work in R1.2

### ISSUE THREAD

**Issue by mskiller** [Crypt1-C/Encrypted_-Modpack#28]
Hi,

I no more get crafting reciepe for almost every item in JEI since updated to r1.2

**Comment by Sedus** [comment]
Do you play on server?

**Comment by tjsd** [comment]
Samme issue for me (yes on a server)

**Comment by Sedus** [comment]
It was good on 1.1?

**Comment by Sedus** [comment]
Works with 1.1 kubejs folder

**Comment by 3733WOLF** [comment]
The jei server bug we are aware of, were trying to find the cause, we will look into a fix as soon as we can find the cause of it to begin with

**Comment by Sedus** [comment]
I think kubejs assets are incomplete
