### ISSUE TITLE
Player Skin

### ISSUE THREAD

**Issue by DrizztsGaming** [Crypt1-C/Encrypted_-Modpack#29]
I have made a server for this pack and when I get on I dont see my skin on the serve. I even tried doing a server on my PC and still get the same issue.

Not sure if im the only one with this issue

**Comment by Premieress** [comment]
There is an announcement in the discord about it. The server was started in offline mode, they are working on changing it.

**Comment by Crypt1-C** [comment]
@DrizztsGaming make sure you change `online-mode=true` in the **server.properties** file
