### ISSUE TITLE
Protactinium not craftable

### ISSUE THREAD

**Issue by mortware** [Crypt1-C/Encrypted_-Modpack#31]
No recipe to create the chemical from anything but itself.

Ingots required for Ultimate Ingot

**Comment by Drackion** [comment]
It is crafted in the Fusion chamber, it is just jei doesn't show the recipes, but to craft the element you need to combine 2 elements together where their combined atomic number equals the number of the element you want to craft.

Take the element Protactinium for example, its atomic number is 91 so we will need to combine 2 element that add up to 91, so we could combine Galium (31) with Neodymium (60) to craft Protactinium as 31+60=91
