### ISSUE TITLE
No Alchemisty recipies 1.8 Pre Release 

### ISSUE THREAD

**Issue by RobotMurl** [Crypt1-C/Encrypted_-Modpack#49]
There are no current recipies for any Alchemistry elements to craft with

**Comment by Premieress** [comment]
did you upgrade to 1.1 release? or 1.2 release solo world?

**Comment by Sedus** [comment]
![image](https://user-images.githubusercontent.com/76965026/183664787-ba0eb677-8a67-489e-bdc7-a80c79222aad.png)

R-1.3
