### ISSUE TITLE
Mahou Tsukai - Villagers

### ISSUE THREAD

**Issue by Epicycle23** [Crypt1-C/Encrypted_-Modpack#50]
This is more of a question but is there even a way to get/spawn villagers?
Since leveling up Morgan requires you to kill villagers how does this work in this pack?

**Comment by Epicycle23** [comment]
Figured it out...
1. Wait for a Zombie Villager to spawn from Dreadful Dirt
2. Capture them and place them in a hole
3. Throw a splash potion of weakness on them
4. give them a golden apple
5. Wait for them to turn into a villager


But uhm, when has the GM chicken feed recipe been disabled?
When I started over after 1.8 I was still able to get an enderman spawn egg.

**Comment by Premieress** [comment]
You can still make golden eggs and rotten eggs in the chemical combiner

**Comment by Epicycle23** [comment]
> You can still make golden eggs and rotten eggs in the chemical combiner

The GM chicken feed makes a spawn egg not a golden/rotten egg.
Swab with DNA + seed + bucket of xp = Spawn egg of the entity the DNA  was taken from.

**Comment by Premieress** [comment]
I've only used the feed for the eggs, not the swab thing. As far as I know it has not been disabled. If you are on version 1.3 or 1.2 try going back to 1.1

**Comment by Epicycle23** [comment]
I am on 1.2 and reading about the recipe issues in 1.3 I'll wait before updating.
I got the villager spawn egg via the Capture enchantment and a mob duplicator so for now I will not try going back to a earlier version, won't risk another world corruption.

**Comment by Premieress** [comment]
yeah if you are solo then 1.2 should be ok. I'm not seeing anything about the swab thing being taken out so will keep it assumed as a bug then if its not showing up in 1.2 on solo world.

**Comment by Epicycle23** [comment]
Found this in the recipes script of cubejs:
```
event.remove({output:` 'mob_grinding_utils:gm_chicken_feed_cursed'})		
event.remove({output: 'mob_grinding_utils:gm_chicken_feed'})
```

looking at the source of the ~~recipe~~ item it looks like the different types of chicken feeds share the same ~~recipe~~ item class so that's probably the reason why the recipe is gone.

**Comment by Premieress** [comment]
alright so keep this open so its seen as a bug then it will get added to the list lol

**Comment by Epicycle23** [comment]
just in case it's really a bug and wasn't disabled intentionally, this seems to fix it:

File: kubejs/server_scripts/recipes.js
Replace line ~~76~~
`event.remove({output: 'mob_grinding_utils:gm_chicken_feed'})`
with
`event.remove({output: 'mob_grinding_utils:nutritious_chicken_feed'})`

Both feeds for golden and rotten egg are still disabled but the one with the swab for spawn eggs is not at least they don't show up in JEI

Edit: just found out that sources are now available on github. in the current version the line has already been removed and the line number is different from what I got (v1.2) 
Edit2: the sources are from pre1.8 =x soooo nevermind you got it
