### ISSUE TITLE
JEI Problems

### ISSUE THREAD

**Issue by Reaksel** [Crypt1-C/Encrypted_-Modpack#51]
When playing a single player map with friends they cant use the JEI recipe controlles to see how to create items, and a verry limited use of what the items can be used for, the problem are not for the one that have made the game, i can see every recipe but only people who join my game cant

**Comment by Premieress** [comment]
1.2 only works for SOLO worlds. Multiplayer even LAN does not work for multiplayer currently. There is a fix in progress and the discord will have an announcement once its updated.
