### ISSUE TITLE
Furnace quest doesn't complete.

### ISSUE THREAD

**Issue by Kahdeg-15520487** [Crypt1-C/Encrypted_-Modpack#53]
![image](https://user-images.githubusercontent.com/15503419/183410405-9beb7c0f-7add-4d97-9bea-fb6570e47b22.png)
As seen in the image above, i have already crafted a furnace but the quest itself doesn't complete.

**Comment by Premieress** [comment]
did you check the player progression quests first?

**Comment by Kahdeg-15520487** [comment]
that seem to be the case, i need to check mark the big one in the progression quest.
