### ISSUE TITLE
As of R-1.3 a bunch of recipes no longer work/don't exist.

### ISSUE THREAD

**Issue by IulianDan** [Crypt1-C/Encrypted_-Modpack#54]
For example, most of the recipes for Iron Furnaces like:
![Invar Gen](https://user-images.githubusercontent.com/32518786/183466621-700b832b-a3f1-4ad9-8119-a42599704e40.png)
or
![Signalum gen](https://user-images.githubusercontent.com/32518786/183466845-ca7a1e97-a52b-46e0-b45e-42e94b1e84e4.png)

I made a list of items that have quests made for them but don't have recipes anymore:

Iron Generators: Bronze Generator, Invar Generator, Signalum Generator. Enderium Generator, Steel Generator
Thermal Series: Igneous Extruder, Induction Smelter, Redstone Furnace, Magma Crucible, All the Dynamos have broken recipes
Create: Empty Blaze Burner, Mechanical Saw (Literally needed to progress), Oredictionificator, Electron Tube
Beyond Earth: All the spacesuit recipes are gone, Compressor, Oxygen Loader, Fuel Loader, Compressed Steel, Nasa Workbench, Oxygen Can (Pretty much all the recipes from this mod are messed up)
Immersive Engineering: Water Wheel, Thermoelectric Generator

I'm sure there are many other broken recipes, but these were all I could find in a few minutes of scrolling through quests.

Edit: Yes, I am also playing on my singleplayer world.

**Comment by IulianDan** [comment]
A bunch of machines from Industrial Foregoing also don't have recipes, such as:
Dissolution Chamber, Black Hole Controller, Bioreactor, some of the generators, Plant Gatherer; Sower; Fertilizer, Mob Slaughter Factory, Animal Rancher; Feeder; Baby Separator, Mob Crusher, Sludge Refiner, Marine Fisher, Potion Brewer, Laser Bases and Laser Drill, Water Condensator, Block Breaker, Fluid Collector; Placer, Dye Mixer, Material Stonework Factory, Enchantment Sorter; Applicator; Extractor.

**Comment by melbellrocks** [comment]
All of the basic Mekanism pipes are also uncraftable/no recipe.  

The Advanced, Elite, and Ultimate versions seem to be fine.

Edit to add:  In case it is worth noting, I am playing in a single player world.  Not sure if previously it was only servers having issues, but now it seems to affect both.

**Comment by Smurfz87** [comment]
Also playing SP world, no additional mods installed, lots of recipes missing. Among others: Rope Pulley, Steam Engine and Steam Whistle from Create.

**Comment by Copperearth** [comment]
None of the recipes show up in jei for me. At least on my 1.3 server with the 1.3 client, I have not tested singleplayer.

**Comment by digitalseraphim** [comment]
Also, the pipes from Create, but the big one is the Electron Tube. It's required to progress, and there doesn't appear to be a way to make it.

**Comment by lmnocat** [comment]
From Mekanism & its add-ons: All the basic pipes, Control Rod Assembly, fission fuel assembly, saturating condenser, turbine casing, electromagnetic coil, rotational complex, turbine rotor, turbine blade, walkie-talkie, fuelwood heater, formulaic assemblicator, solar neutron activator, personal chest, personal barrel, radioactive waste barrel, security desk, boiler casing,pressure disperser, induction casing, module base scuba mask, and oredictionificator

From Create & its add-ons: Glowing Ingot, Grappling whisk, nixie lamp,brass globe, radiant casing, empty spool, zink sheet,capacitor,rolling mill, alternator, wand of symmetry, extendo grip, minecart coupling,super glue, Engineer's goggles, wrench,electron tube,whisk, propeller, haunted bell, peculiar bell, rose quartz lamp,display board, display link,brass tunnel, brass funnel, item vault, flywheel,mechanical plough, mechanical harvester, redstone contact, mechanical saw,rope pulley,steam whistle, steam engine, hose pulley, fluid tank, fluid valve, fluid pipe, copper ladder, metal girder, chute, weighted ejector, empty blaze burner, and brass gilded lapis lazuli.

 all have broken recipes

**Comment by IulianDan** [comment]
R-1.4 Has fixed these issues.
