### ISSUE TITLE
Guidebook in R-1.3 not working?

### ISSUE THREAD

**Issue by Trogdayton** [Crypt1-C/Encrypted_-Modpack#56]
It just shows up in my inventory as invalid patchouli guide. Feel free to ignore the emc tag. I always add Project E for testing purposes when playing with new packs.
![image](https://user-images.githubusercontent.com/93630831/183540208-55e2e168-b5bb-4bde-8fb4-824b88f49f12.png)
I'm assuming it's perhaps just not linking to the content correctly? Or if it is, then it's a bug on my end. Either way I'd like to know. Thanks! Your pack is fun so far!

**Comment by djacu** [comment]
I'm seeing the same issue.
![image](https://user-images.githubusercontent.com/7043297/183561807-e49570f2-4399-4bbc-9231-939cdefc776e.png)

**Comment by Sir-Antonic** [comment]
Has happened to me as well
![2022-08-09 12_41_07-Encrypted_ Release 1 3](https://user-images.githubusercontent.com/8020285/183722863-d5266823-3f27-4a51-b6ce-ceeae8ca8bee.png)
