### ISSUE TITLE
Steel Plate und Servo Press

### ISSUE THREAD

**Issue by Klausenchiller** [Crypt1-C/Encrypted_-Modpack#57]
Da das Metallergic infuser rezept für das steel casing von Mekanism entfernt wurde bzw nur ohne mekanism Stahlblöcke funktioniert, ist die Create- Lösung Naheliegend. Allerdings ist die Thermal Expansion Servo Press als Rezept deaktiviert und es gibt keine Alternative für die Steel Plate über create o. a.

**Comment by Epicycle23** [comment]
Ich nehme an du bist auf R1.3?
Und ich glaube auf Englisch  kommst du hier weiter, kann mich aber auch irren ;)
