### ISSUE TITLE
empty blaze burner not craftable

### ISSUE THREAD

**Issue by awsmaythem** [Crypt1-C/Encrypted_-Modpack#59]
No recipe to create the (empty blaze burner) from anything
![2022-08-09_17 34 14](https://user-images.githubusercontent.com/85623714/183676604-234fdd5f-c33e-4d9b-8973-eb119d84bd09.png)
.

**Comment by Premieress** [comment]
There is already a github post with an extensive list that we are asking players to add to in the comments. Please post any recipes that arent already listed there that you find are missing.
