### ISSUE TITLE
All ChemLib items in storage gone after upgrade from 1.3 to 1.4

### ISSUE THREAD

**Issue by Smurfz87** [Crypt1-C/Encrypted_-Modpack#65]
All items from ChemLib that was in storage seems to have been removed from my storage drawers / refined storage after updating.
Player warning on upgrade is adviced in release log.

**Comment by Premieress** [comment]
It was posted in the announcements on the discord. Not everyone uses the discord, but the information is there for people looking.

**Comment by Smurfz87** [comment]
I'd still argue it warrants a note in the changelog. Personally I don't mind much as I mainly store items and not elements, but a bit annoying :) Especially knowing it was a known issue posted elsewhere...

**Comment by Premieress** [comment]
I'll make a note of it for the dev. The civil communication discussing something frustrating is appreciated.
