### ISSUE TITLE
[R-1.4] wrong Thermal's phytogenic insolator catalyst

### ISSUE THREAD

**Issue by Overseer9** [Crypt1-C/Encrypted_-Modpack#66]
Updated to 1.4 but phytogenic insolator catalyst still uses pulverizer's catalyst and not its own catalyst

**Comment by Sedus** [comment]
Phytogenic insolator don't accept the pulverizer's catalyst (flint and bazalz powder).
Works fine with its own catalyst (phyto-gro, bone meal, compost).
However, it shows incorrectly inside phytogenic insolator->show recipes, but this is only visual bug. (Known bug)

R-1.5
