### ISSUE TITLE
No Recipe to craft the initial Andesite Casings needed to start going into tech

### ISSUE THREAD

**Issue by nastro1995** [Crypt1-C/Encrypted_-Modpack#67]
No Recipe to craft the initial Andesite Casings needed to start going into tech, only shows the sequence crafting mechanic.

I did try placing a wooden machine casing in world and right or left clicking with an andesite alloy(s)

**Comment by MrMonkeys** [comment]
For me right clicking a wood machine frame with andesite alloy work

**Comment by nastro1995** [comment]
I did place a few wooded machine frames in world as i stated in my second sentence and does not work and tried both left- and right- clicking , but nothing happens
