### ISSUE TITLE
R_1.4 Cannot make iron.

### ISSUE THREAD

**Issue by DefaultLP** [Crypt1-C/Encrypted_-Modpack#71]
I started playing today and now I am apparently stuck. 
I need the Compactor to make iron, but I also need 6 iron to make the Compactor.
There seems to be no way to progress beyond this point.

**Comment by MrMonkeys** [comment]
Before this version you maked iron with combiner but now it’s with compactor, give you one it’s maybe a bug.

**Comment by Werewolf74** [comment]
Hi, is hard way but you can made obsidian and diamond with the combiner so you can made the portal to mining world , Iron you can farming there.

**Comment by Tlotro** [comment]
> Before this version you maked iron with combiner but now it’s with compactor, give you one it’s maybe a bug.

for compactor you need iron.
