### ISSUE TITLE
Unlimited Diamond with the Alchemestry Combiner. Oo

### ISSUE THREAD

**Issue by Werewolf74** [Crypt1-C/Encrypted_-Modpack#72]
Modpack. Encrypted_-R-1.4
Mod. Alchemistry

This bug works in energy loaded Alchemistry: Combiner select diamond recipe, put first in the second slot 64 Graphite then put only 1 Graphite in the first slot and the magic is going on, it lost only energy to produce diamond so you can made it unlimited.

Second thing is if you put first slot 64 Graphite and second slot only 1 you produce a Diamond and lost 65 Graphite instead of 2 x 64 Graphite.

regards.

**Comment by Jin16** [comment]
Already known and fix by the mod dev https://github.com/SmashingMods/Alchemistry/issues/232

**Comment by Werewolf74** [comment]
Oh ok thx. <closed>
