### ISSUE TITLE
Missing Sugar/Sugarcane

### ISSUE THREAD

**Issue by zasroman** [Crypt1-C/Encrypted_-Modpack#73]
Sugar is a recipe that requires sugar to use as a target in the new _Chemistry_ update. There isn't a way to obtain sugar other than using the honey bottle in the E Shop quest-line. Sugar is used in the Dark Utilities vector plates. Maybe the recipe should be moved back to the combiner? R-1.4

**Comment by Premieress** [comment]
1.4 update changed tags and recipes got removed because of the mod updating. Apples give sucrose though so that should be able to be made into sugar.

**Comment by zasroman** [comment]
The sugar recipe is in the compactor. The recipe is essentially one sugar and one sucrose give two sugar. I agree that it is only sucrose, but the compactor requires the target item to be clicked into the upper slot before it starts working. If you do not have any sugar, you do not get sugar. The modpack does not give you sugar. If you've used the last of the sugar like I have, you're stuck.

**Comment by Premieress** [comment]
The recipe didnt used to be that way. You'd get sucrose from apples and that would be turned into sugar in the compactor. Like I said though, 1.4 changed recipes, it wasn't anything this modpack chose to do. No eta for fix yet though as it erased all our recipes that were for those mods.

**Comment by zasroman** [comment]
shift clicking sucrose into the compactor works now, have access to all the recipes without having to build a pokedex
