### ISSUE TITLE
Wrong chest when using log recipe

### ISSUE THREAD

**Issue by luca1197** [Crypt1-C/Encrypted_-Modpack#74]
Version: 1.4

When crafting a chest using planks (e.g. oak planks), you will get the correct chest from Quark (e.g. Oak Chest).
But when using logs instead of planks to craft 4 chests, you will get the vanilla Minecraft chest, but the Quark chest was supposed to be the result of this recipe I guess.

Screenshots:
![javaw_Kvfduol9Or](https://user-images.githubusercontent.com/33791936/185261356-bfba7cbf-ea0e-42ba-841c-77ff9054d53c.png)
![javaw_lfKDx4iXjR](https://user-images.githubusercontent.com/33791936/185261359-b48619a2-6c0e-4379-b9d1-8330662261bc.png)

**Comment by kalutro** [comment]
If you click the button above the output slot, you can choose which chest to make.

**Comment by luca1197** [comment]
Oh, I see, thanks for pointing that out! I think it would still be great if the default recipe would be changed to the Quark chests, if that is even possible, just to improve the UX a tiny bit, in my opinion.
