### ISSUE TITLE
Ore dictionary issues

### ISSUE THREAD

**Issue by Epicycle23** [Crypt1-C/Encrypted_-Modpack#8]
I am not sure if this can be called a bug but it certainly makes dealing with ores/ingots/nuggets/etc. kind of difficult.
Some ores/ingots/nuggets/etc. turn into a different variant when picked up.
Yellorite ore for example turns into uranium ore when picked up (extreme example because usually it is just one ore turning into another variant from a different mod when picked up).
This makes it kind of difficult to organize ores coming in through any means of automation in storage drawers because one is not able to setup a drawer with yellorite without piping the ore into a drawer instead of just picking the ore up and putting it into a drawer.
~~Same goes for liquids, when pickung up xp with the absorption hopper and pushing it into a jumbo tank it turns into a different variant of liquid experience and  prevents further insertion because of it.~~
I am not sure if this is in any way fixable but I have to say I never had so much trouble with this kind of stuff before.

**Comment by Epicycle23** [comment]
PS: I am not able to reproduce the liquid xp issue, maybe the liquid got in there because I messed up somewhere (most certainly now that I look at my setup ;)

**Comment by Crypt1-C** [comment]
unifying ores and ingots is essential as you will have a mess of stuff say for example 5 different types of tin or even lead 
however i might look for fix asap
