### ISSUE TITLE
Generators From Iron Generators Don't Drop Themselves When Broken

### ISSUE THREAD

**Issue by MaxAstro** [Crypt1-C/Encrypted_-Modpack#81]
Tested with the stone and iron generators, which is as far as I've gotten so far - both are destroyed if you try to pick them up.

**Comment by 3733WOLF** [comment]
https://github.com/Crypt1-C/Encrypted_-Modpack/issues/1

**Comment by 3733WOLF** [comment]
its an issue with tinkers
