### ISSUE TITLE
Items already in the input slot of the Compactor get deleted when sending a recipe from JEI.

### ISSUE THREAD

**Issue by kalutro** [Crypt1-C/Encrypted_-Modpack#82]
Items already in the input slot of the Compactor get deleted when sending a recipe from JEI.

Steps:
 - Put item into input slot of the Compactor. I used a stack of Silicon Dioxide.
 - Send recipe from JEI. I used Andesite.
 - The Silicon Dioxide already in the Compactor is deleted and 1 Silicon Dioxide from my inventory is used.

Notes: I notice this happens if I put the items into the Compactor before I choose a recipe. I could avoid this by choosing a recipe first. I assume this is a bug.

**Comment by Sedus** [comment]
The other 63 Silicon Dioxide should be in your inventory.

**Comment by kalutro** [comment]
Not sure how this is invalid unless I am missing something. The items are definitely not returning to my inventory. I created a short GIF to show the issue I am having. Since this is marked as wontfix, I guess just be careful!

![javaw_BdJhjTT9RS](https://user-images.githubusercontent.com/69569507/185812258-4f647f37-27c7-481d-92a6-85c649d1f752.gif)

**Comment by Crypt1-C** [comment]
that's a mod bug 
not the modpack's bug

**Comment by Sedus** [comment]
Hold on, what version is this?
@kalutro

**Comment by kalutro** [comment]
Encrypted_ R-1.5, Alchemistry 2.0.6

**Comment by Sedus** [comment]
Oh, Latest is R-1.8 which has Alchemistry 2.0.8a

**Comment by Sedus** [comment]
Wooo this is very tricky you must have 2 stacks, I tried with only one, thanks for the GIF. Btw, this is fixed in the latest version.
