### ISSUE TITLE
IntegratedREST-1.18.2-1.1.5 is causing a server tick loop

### ISSUE THREAD

**Issue by blacksythe** [Crypt1-C/Encrypted_-Modpack#85]
java.net.BindException: Address already in use

Some background on this.
The server is running Amp Cubecoders backend server software with multiple live servers all currently in use. Currently 2 -1.12.2, 2 - 1.16.5 and a 1.18.2 server

The ip for the local server box is using a loopback address (127.0.0.1 and 0.0.0.0 tested)

The port has been checked with 25566 and 25571, both return the same error

The process list for the box has been checked and there are no ghost processing running on either of these ports.

Normally when there is a crash relating to address or ports in use it happens much sooner.

2 different forge versions have been tested the one that comes with the pack and the newer one.

I have booted up a vanilla forge server on both of these ports and they boot fine.
I have booted direwolf 1.18.2 on both of these ports and it works fine.

Crash report included.
[crash-2022-08-28_17.46.45-server.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9440549/crash-2022-08-28_17.46.45-server.txt)

[debug excert.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9440551/debug.excert.txt)

[latest.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9440553/latest.txt)

Reviewing the files i determined that the problem mod is IntegratedREST-1.18.2-1.1.5.jar

disabling it booted the server

**Comment by blacksythe** [comment]
https://github.com/CyclopsMC/IntegratedREST/issues/22

**Comment by 3733WOLF** [comment]
removed mod
