### ISSUE TITLE
extreme reactors graphite bar  no recipe

### ISSUE THREAD

**Issue by nooboxstudio** [Crypt1-C/Encrypted_-Modpack#86]
there is only the recipe from dust to ingot and from ingot to dust.
![Captura de Tela (31)](https://user-images.githubusercontent.com/10349320/187317703-887f4844-5ac3-4993-b318-5885f73ef865.png)
![Captura de Tela (30)](https://user-images.githubusercontent.com/10349320/187317706-620fbe84-2352-499d-b066-d42f77616003.png)

**Comment by 3733WOLF** [comment]
look at the block of graphite recipe
