### ISSUE TITLE
Fail to start the pack

### ISSUE THREAD

**Issue by comoaig** [Crypt1-C/Encrypted_-Modpack#88]
When i start the pack it says this

![image](https://user-images.githubusercontent.com/112703312/188140785-462e5eb7-dba9-439a-adca-20c0d7716dea.png)

[crash-2022-09-02_14.09.52-fml.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9477748/crash-2022-09-02_14.09.52-fml.txt)
[latest.log](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9477751/latest.log)

**Comment by Feafroth** [comment]
I'd created a new instance (Change version -> update to new profile) and copy all folders from this to old instance with replace. This helped me to fix this issue
